<!DOCTYPE html>
<html lang="cs">                                                                                         
  <head>                                                                                                                                                     
    <meta charset="UTF-8" />                                                                                                                                                     
    <meta name="google-site-verification" content="-D-v-nN3c_muNYLaLhjbqISzugHO0N7vrv9gmCuN1DY" />                                                                                                                                                     
    <meta name="description" content="Lineage 2 Interlude Test server pro všechny co to chtějí zkusit." />                                                                                                                                                     
    <meta name="keywords" content="L2,OnlineGame,Lineage 2, Interlude" />                                                                                                                                                     
    <meta name="author" content="Tomáš Gánoci" />                                                                                                                                                     
    <meta name="robots" content="index, follow" />                                                                                                                                                     
    <link rel="shortcut icon" href="templates/l2/images/favicona.png" />                                                                                                                                                         
    <link rel="stylesheet" type="text/css" href="templates/l2/css/style.css" />                                                                                                                                                                                                                
    <title>Lineage 2 Interlude                                                                                                                                                            
    </title>     
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-45698416-2', 'sachasport.cz');
  ga('send', 'pageview'); 
</script>                                                                                                                                                             
  </head>                                                                                         
  <body>                                                                                                                                                                                                                                                                                                           
    <div id="web">                                                                                                                                                                                                                                                                     
      <div id="header">                                                                                                                                                                                                                                                                                                                                     
        <a href="index.php"><h1>Logo</h1>                                                                        
          <div id="logo">                                                                                                                                                           
          </div></a>                                                                                                                                                                                                                            
        <div id="menu">                                                                                                                                                                                                                                                                          
          <nav>                                                                                                                                                                                                                                                                                                                        
            <?php include "templates/l2/bars/menu.php" ?>                                                                                                                                                                                                                                                                                                
          </nav>                                                                                                                                                                                                                            
        </div>                                                                                                                                                                                                                                                                                                                                                      
      </div>
      <div id="site">                                                                                                                                                 
        <div id="side-left">                                                                                                                                      
          <div class="nav-menu">                                                                                                                                                                     
            <div class="nav-menu-top">            <h2>                                                 Statistics                                                 </h2>                                                                                                                                                           
            </div>                                                                                                                                                                     
            <div class="nav-menu-mid">                                                                                                                                                                                                                                                                                                                
              <?php include "templates/l2/bars/statistic.php" ?>                                                                                                                                                                                    
            </div>                                                                                                                                                                     
            <div class="nav-menu-bottom">                                                                                                                                                         
            </div>                                                                                                                                                                                          
          </div>                                                                                                                                                                                                                                                   
          <div class="nav-menu">                                                                                                                                                                     
            <div class="nav-menu-top">            <h2>                                                 Vote Fo Us                                                 </h2>                                                                                                                                                           
            </div>                                                                                                                                                                     
            <div class="nav-menu-mid">                                                                                                                                                                                                                                                                                                                
              <?php include "templates/l2/bars/vote.php" ?>                                                                                                                                                                                    
            </div>                                                                                                                                                                     
            <div class="nav-menu-bottom">                                                                                                                                                         
            </div>                                                                                                                                                                                          
          </div>                                                                                                                                                            
        </div>                                                                            
        <div id="side-mid">                                                                                                                                                                                       
          <div class="nav-menu">                                                                                                                                                                   
            <div class="nav-mid-top">                                                                                                                                                        
            </div>                                                                                                                                                                   
            <div class="nav-mid-mid">                       
              <?php include "main.php" ?>                                                                         
            </div>                                                                                                                                                        
            <div class="nav-mid-bottom">                                                                                                                                                       
            </div>                                                                                                                                                                                        
          </div>                                                                            
        </div>                                                                                                
        <div id="side-right">                                                                                                                                                                   
          <div class="nav-menu">                                                                                                                                                                     
            <div class="nav-menu-top">            <h4>                                                Server Status                                                 </h4>                                                                                                                                                           
            </div>                                                                                                                                                                     
            <div class="nav-menu-mid">                                      
                                       
              <div class="css">
              <a href="http://seo-servis.cz/source-zdrojovy-kod/9948702" title="SEO Servis, optimalizace pro vyhledávače.">                                            
                <img src="http://seo-servis.cz/optimised.png" height:"15" width="80"  alt="Seo servis" /></a>                                                                                                                                   
                <a href="http://jigsaw.w3.org/css-validator/check/referer">                                        
                  <img src="http://jigsaw.w3.org/css-validator/images/vcss-blue"         alt="Ověřit CSS!" /></a>
                  <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.sachasport.cz%2Ftomas%2Flineage2%2F"><img src="templates/l2/images/validator.png" alt="validator.png, 345B" title="validator" height="15" width="80">
                                                                                                                   </a>                                                                                                                              
              </div>                                                                                                                                                                                                                                                                                                                                                                                   
            </div>                                                                                                                                                                     
            <div class="nav-menu-bottom">                                                                                                                                                         
            </div>                                                                                                                                                                                          
          </div>                                                                                                                                                                                                                                                                                                    
          <div class="nav-menu">                                                                                                                                                                     
            <div class="nav-menu-top">            <h4>                                                Server Statistic                                                 </h4>                                                                                                                                                           
            </div>                                                                                                                                                                     
            <div class="nav-menu-mid">                                                                                                                                                                                                                                                                                                                                                                                     
            </div>                                                                                                                                                                     
            <div class="nav-menu-bottom">                                                                                                                                                         
            </div>            
          </div>                                                                                                                                                                                          
        </div>                                                                                                                                                                                                                                               
      </div>                                                                                                     
    </div>                                                                                                                                                                   
    <div class="footer">    <strong>Designet by Gony</strong>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
      <address>Tomáš Gánoci                                                                                                                                                                                                                                                                                                                                                                             
        <br>                                                                                                                                                                                                                                                                                                                                                                            
        <a href="mailto:gony65@gmail.com">Gony65@gmail.com</a>                                                                                                                                                                                                                                                                                                                  
      </address>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    </div>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
  </body>
</html>